baseURL: /
languageCode: en-us
paginate: 12
Copyright: Icarusky
googleAnalytics: ""
menu:
  main:
    - Identifier: articles
      Name: 文章
      URL: /articles/
      Weight: '10'

    - Identifier: physics
      Name: 物理
      URL: /categories/physics/
      Weight: '110'
      parent: "articles"

    - Identifier: literature
      Name: 文学
      URL: /categories/literature/
      Weight: '120'
      parent: "articles"

    - Identifier: art
      Name: 艺术
      URL: /categories/art/
      Weight: '130'
      parent: "articles"

    - Identifier: rambling
      Name: 杂谈
      URL: /categories/rambling/
      Weight: '140'
      parent: "articles"

    - Identifier: photography
      Name: 摄影
      URL: /photography/
      Weight: '20'

    - Identifier: friends
      Name: 友链
      URL: /friends/
      Weight: '30'

    - Identifier: about
      Name: 关于
      URL: /about/
      Weight: '40'

    - Identifier: contact
      Name: 联系
      URL: /contact/
      Weight: '50'
    
taxonomies:
  category: categories
  tag: tags
title: "Icarusky: a student's blog"
disableFastRender: true
disqusShortname: "glennmccomb-com"

# Related.
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: categories
      weight: 130
      includeNewer: true
